# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icons8-zip-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(24, 24))
        self.tabWidget.setObjectName("tabWidget")
        self.NewTab = QtWidgets.QWidget()
        self.NewTab.setObjectName("NewTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.NewTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.NewList = QtWidgets.QTreeWidget(self.NewTab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.NewList.setFont(font)
        self.NewList.setObjectName("NewList")
        self.gridLayout_2.addWidget(self.NewList, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.DestinationInput = QtWidgets.QLineEdit(self.NewTab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DestinationInput.setFont(font)
        self.DestinationInput.setObjectName("DestinationInput")
        self.horizontalLayout.addWidget(self.DestinationInput)
        self.NewSelectDestBtn = QtWidgets.QPushButton(self.NewTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.NewSelectDestBtn.setFont(font)
        self.NewSelectDestBtn.setObjectName("NewSelectDestBtn")
        self.horizontalLayout.addWidget(self.NewSelectDestBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.NewTab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.AddFileBtn = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.AddFileBtn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/icons8-plus-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AddFileBtn.setIcon(icon1)
        self.AddFileBtn.setObjectName("AddFileBtn")
        self.RemoveFileBtn = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RemoveFileBtn.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/icons8-erase-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RemoveFileBtn.setIcon(icon2)
        self.RemoveFileBtn.setIconSize(QtCore.QSize(24, 24))
        self.RemoveFileBtn.setObjectName("RemoveFileBtn")
        self.ClearListBtn = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ClearListBtn.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/icons8-refresh-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ClearListBtn.setIcon(icon3)
        self.ClearListBtn.setIconSize(QtCore.QSize(24, 24))
        self.ClearListBtn.setObjectName("ClearListBtn")
        self.CreateZipBtn = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CreateZipBtn.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/icons8-add-file-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CreateZipBtn.setIcon(icon4)
        self.CreateZipBtn.setIconSize(QtCore.QSize(24, 24))
        self.CreateZipBtn.setObjectName("CreateZipBtn")
        self.gridLayout_2.addWidget(self.splitter, 2, 0, 1, 1)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/icons8-add-file-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.NewTab, icon5, "")
        self.ExtractTab = QtWidgets.QWidget()
        self.ExtractTab.setObjectName("ExtractTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ExtractTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ExtractList = QtWidgets.QTreeWidget(self.ExtractTab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ExtractList.setFont(font)
        self.ExtractList.setObjectName("ExtractList")
        self.gridLayout_3.addWidget(self.ExtractList, 1, 0, 1, 4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ExtractDestInput = QtWidgets.QLineEdit(self.ExtractTab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ExtractDestInput.setFont(font)
        self.ExtractDestInput.setObjectName("ExtractDestInput")
        self.horizontalLayout_2.addWidget(self.ExtractDestInput)
        self.ExtractDestBtn = QtWidgets.QPushButton(self.ExtractTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ExtractDestBtn.setFont(font)
        self.ExtractDestBtn.setObjectName("ExtractDestBtn")
        self.horizontalLayout_2.addWidget(self.ExtractDestBtn)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 0, 1, 4)
        self.ExtractFileInput = QtWidgets.QLineEdit(self.ExtractTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExtractFileInput.sizePolicy().hasHeightForWidth())
        self.ExtractFileInput.setSizePolicy(sizePolicy)
        self.ExtractFileInput.setObjectName("ExtractFileInput")
        self.gridLayout_3.addWidget(self.ExtractFileInput, 0, 0, 1, 3)
        self.ExtractSelectBtn = QtWidgets.QPushButton(self.ExtractTab)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/icons8-file-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ExtractSelectBtn.setIcon(icon6)
        self.ExtractSelectBtn.setIconSize(QtCore.QSize(24, 24))
        self.ExtractSelectBtn.setObjectName("ExtractSelectBtn")
        self.gridLayout_3.addWidget(self.ExtractSelectBtn, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(244, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 3, 0, 1, 1)
        self.ExtractBtn = QtWidgets.QPushButton(self.ExtractTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExtractBtn.sizePolicy().hasHeightForWidth())
        self.ExtractBtn.setSizePolicy(sizePolicy)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/icons8-zip-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ExtractBtn.setIcon(icon7)
        self.ExtractBtn.setIconSize(QtCore.QSize(24, 24))
        self.ExtractBtn.setObjectName("ExtractBtn")
        self.gridLayout_3.addWidget(self.ExtractBtn, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(244, 29, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 3, 3, 1, 1)
        self.tabWidget.addTab(self.ExtractTab, icon7, "")
        self.InfoTab = QtWidgets.QWidget()
        self.InfoTab.setObjectName("InfoTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.InfoTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.FileInfoInput = QtWidgets.QLineEdit(self.InfoTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FileInfoInput.sizePolicy().hasHeightForWidth())
        self.FileInfoInput.setSizePolicy(sizePolicy)
        self.FileInfoInput.setObjectName("FileInfoInput")
        self.gridLayout_5.addWidget(self.FileInfoInput, 0, 0, 1, 2)
        self.FileInfoList = QtWidgets.QTreeWidget(self.InfoTab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.FileInfoList.setFont(font)
        self.FileInfoList.setObjectName("FileInfoList")
        self.gridLayout_5.addWidget(self.FileInfoList, 1, 0, 1, 3)
        self.FileSelectBtn = QtWidgets.QPushButton(self.InfoTab)
        self.FileSelectBtn.setIcon(icon6)
        self.FileSelectBtn.setIconSize(QtCore.QSize(24, 24))
        self.FileSelectBtn.setObjectName("FileSelectBtn")
        self.gridLayout_5.addWidget(self.FileSelectBtn, 0, 2, 1, 1)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("images/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.InfoTab, icon8, "")
        self.AboutTab = QtWidgets.QWidget()
        self.AboutTab.setObjectName("AboutTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.AboutTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.AboutTab)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.AboutTab)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.tabWidget.addTab(self.AboutTab, icon, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyZip"))
        self.NewList.headerItem().setText(0, _translate("MainWindow", "File name"))
        self.NewList.headerItem().setText(1, _translate("MainWindow", "Date"))
        self.NewList.headerItem().setText(2, _translate("MainWindow", "File size"))
        self.DestinationInput.setPlaceholderText(_translate("MainWindow", "Enter the desitnation"))
        self.NewSelectDestBtn.setText(_translate("MainWindow", "Select Folder"))
        self.AddFileBtn.setText(_translate("MainWindow", "Add file"))
        self.RemoveFileBtn.setText(_translate("MainWindow", "Remove file"))
        self.ClearListBtn.setText(_translate("MainWindow", "Clear list"))
        self.CreateZipBtn.setText(_translate("MainWindow", "Create zip"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.NewTab), _translate("MainWindow", "New"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.NewTab), _translate("MainWindow", "Create new zip"))
        self.ExtractList.headerItem().setText(0, _translate("MainWindow", "File name"))
        self.ExtractList.headerItem().setText(1, _translate("MainWindow", "Date"))
        self.ExtractList.headerItem().setText(2, _translate("MainWindow", "File size"))
        self.ExtractDestInput.setPlaceholderText(_translate("MainWindow", "Choose the destination folder"))
        self.ExtractDestBtn.setText(_translate("MainWindow", "Select folder"))
        self.ExtractFileInput.setPlaceholderText(_translate("MainWindow", "Select a file"))
        self.ExtractSelectBtn.setToolTip(_translate("MainWindow", "Select a file"))
        self.ExtractSelectBtn.setText(_translate("MainWindow", "Select file"))
        self.ExtractBtn.setToolTip(_translate("MainWindow", "Select a file"))
        self.ExtractBtn.setText(_translate("MainWindow", "Extract"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ExtractTab), _translate("MainWindow", "Extract"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.ExtractTab), _translate("MainWindow", "Extract zip file"))
        self.FileInfoInput.setPlaceholderText(_translate("MainWindow", "Select a file"))
        self.FileInfoList.headerItem().setText(0, _translate("MainWindow", "File name"))
        self.FileInfoList.headerItem().setText(1, _translate("MainWindow", "Date"))
        self.FileInfoList.headerItem().setText(2, _translate("MainWindow", "File size"))
        self.FileSelectBtn.setToolTip(_translate("MainWindow", "Select a file"))
        self.FileSelectBtn.setText(_translate("MainWindow", "Select file"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.InfoTab), _translate("MainWindow", "File Info"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.InfoTab), _translate("MainWindow", "Get zip file information"))
        self.label.setText(_translate("MainWindow", "PyZip v1.0"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>Created by Joseph Benoy</p><p><a href=\"https://github.com/joseph-benoy\"><span style=\" text-decoration: underline; color:#0000ff;\">Follow me on Github</span></a></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AboutTab), _translate("MainWindow", "About"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.AboutTab), _translate("MainWindow", "About us"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
